name: rro_web
description: My Portoflio Websiter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.5+5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Base Ui
  cupertino_icons: ^1.0.2
  collapsible_sidebar: ^2.0.3+2
  responsive_grid: ^2.1.0
  photo_view: ^0.14.0

  # Responsive
  responsive_sizer: ^3.1.1

  # Timeline Line
  timeline_tile: ^2.0.0

  #Model Gen
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  #State Management
  flutter_bloc: ^8.1.1

  #URl Launch
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

  #Model Gen
  freezed: ^2.2.0
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/trinusa/home/
    - assets/images/trinusa/login/
    - assets/images/trinusa/trinusa/
    - assets/images/trinusa/pbl/
    - assets/images/trinusa/tti/
    - assets/images/nemob/home/
    - assets/images/nemob/login/
    - assets/images/nemob/order/
    - assets/images/nemob/reservation/
    - assets/images/merdeka/
  fonts:
    - family: Proxima
      fonts:
        - asset: assets/fonts/proxima_regular.otf

